Nova rota inpe
alagamentos/floodprediction pull request #2
Opened 2022-05-17 14:09 UTC by Rangel07

Alteração de rota de consumo dos dados do INPE e adição de modelo WRF07X07 km.
Um dos sites utilizados para obter dados de mapa parou de funcionar, por isso foi comentado no código.

Eu não alterei os arquivos em rawdata/Info pluviometricas, imagino que o Makefile possa ter causado algo.

**IMPORTANTE**: O modelo WRF05X05 km será descontinuado em junho.

2022-05-17 16:17 UTC, Kaisen-san requested changes
Deixei alguns comentários, fique à vontade para respondê-los. Obrigado pelas mudanças! 💯

2022-05-18 15:32 UTC, Rangel07 commented on src/Pipeline/download_bigquery.py
> +CREDENTIALS = service_account.Credentials.from_service_account_file('/home/gmrsilva/Documents/floodprediction/key/temporal-285820-5448c1d52cdb.json')
Creio que tenha feito de forma errada e usei o caminho inteiro da minha máquina

2022-05-18 15:36 UTC, Rangel07 commented on src/Dash/cptec.py
> +        f'http://ftp.cptec.inpe.br/modelos/tempo/WRF/ams_07km/recortes/grh/json/{ano}/{mes}/{int(dia)-1}/00/4704.json').json()
Sim, fica bem mais limpo e fácil de visualizar no código! Valeu!

2022-05-18 15:40 UTC, Rangel07 commented on src/Dash/cptec.py
> +  #Dados puros
Sim, acabei comentando por costume essa parte. Valeu pela dica!

2022-05-18 15:53 UTC, Rangel07 commented on src/Dash/main.py
> +precipitacao_path = 'src/Dash/data/Precipitacao.csv'
Ok, mudarei para o que estava antes!

2022-05-18 15:59 UTC, Rangel07 commented
Mudanças feitas! Muito obrigado pelas dicas!

2022-05-22 03:24 UTC, Kaisen-san approved these changes
Desculpa a demora, acabei esquecendo de revisar novamente. Looks good to me! 💎

2022-05-22 03:24 UTC, merged